/*import { Inter } from 'next/font/google'
import './globals.css'
import user from '../app/public/user.svg'

const inter = Inter({ subsets: ['latin'] })*/

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Secao({children,imagem}) {
  return(
    <p>
      {children}
    </p>
  )
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Secao>Home</Secao>
        <Secao>Search</Secao>
        <Secao>Your Library</Secao>
        {children}</body>
    </html>

  )
}

