import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function Secao({ children, icon }) {
  return (
    <p>
      {icon && <img src={`/icons/${icon}`} alt="Icon" style={{ marginRight: '5px' }} />}
      {children}
    </p>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        {/* Adicione outras tags de cabeçalho conforme necessário */}
      </head>
      <body>
        <div className="container-nav">
          <Secao icon="user.svg">Home</Secao>
          <Secao icon="search.svg">Search</Secao>
          <Secao icon="library.svg">Your Library</Secao>
        </div>
        <div className="container-funcoes">
          <Secao icon="playlist.svg">Criar Playlist</Secao>
          <Secao icon="favorites.svg">Seus Favoritos</Secao>
        </div>
        {children}
      </body>
    </html>
  );
}
