
/*import { Inter } from 'next/font/google'

import user from '../app/public/user.svg'

const inter = Inter({ subsets: ['latin'] })*/
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Secao({ children, imagem }) {
  return (
    <p>
      {children}
    </p>
  )

}
///
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container-nav">
          <Secao>Home</Secao>
          <Secao>Search</Secao>
          <Secao>Your Library</Secao>
        </div>
        <div className="container-funcoes">
          <Secao>Criar Playlist</Secao>
          <Secao>Seus Favoritos</Secao>
        </div>
        {children}</body>
    </html>

  )
}
